/// <reference types="vite/client" />

// Virtual content module — shape generated by vite-content-plugin.ts at build time
declare module 'virtual:content' {
  export const SITE_CONFIG: {
    name: string;
    url: string;
    email: string;
    tagline: string;
  };

  export const ROUTE_META: Record<
    string,
    { title: string; description: string; canonical: string }
  >;

  export const HOME_HERO: {
    title: string;
    subtitle: string;
    cta_primary: string;
    cta_primary_href: string;
    cta_secondary: string;
    cta_secondary_href: string;
    content: string;
    seo_title?: string;
    seo_description?: string;
  };

  export const HOME_WHAT_YOU_GET: {
    title: string;
    items: Array<{ icon: string; title: string; desc: string }>;
    subscriberNote: string;
  };

  export const HOME_PROBLEM: {
    title: string;
    subtitle: string;
    intro: string;
    sections: Array<{ title: string; items: string[] }>;
  };

  export const HOME_HOW_IT_WORKS: {
    title: string;
    heading?: string;
    headingHighlight?: string;
    intro?: string;
    steps: Array<{ number: number; title: string; description: string }>;
    comparison: { other: string; sivussa: string };
    comparisonHeading?: string;
    comparisonHeadingHighlight?: string;
    comparisonTable?: { headers: string[]; rows: Record<string, string>[] };
    whatYouGet?: Array<{ title: string; desc: string }>;
    ctaTitle?: string;
    ctaSubtitle?: string;
    ctaText?: string;
    ctaHref?: string;
  };

  export const HOME_FEATURES: {
    title: string;
    subtitle: string;
  };

  // FEATURES passes through raw frontmatter — markdown uses "description"
  export const FEATURES: Array<{ title: string; description: string }>;

  export const HOME_WHO_IS_THIS_FOR: {
    title: string;
    // Plugin maps description -> desc
    cards: Array<{ title: string; desc: string }>;
  };

  export const HOME_PRICING: {
    title: string;
    subtitle: string;
  };

  export const PRICING_TIERS: Array<{
    name: string;
    price: string;
    period: string;
    features: string[];
    popular: boolean;
    ctaText: string;
    ctaHref: string;
  }>;

  export const PRICING_FAQ: Array<{ question: string; answer: string }>;

  export const PRICING_FEATURE_TABLE: {
    headers: string[];
    rows: Record<string, string>[];
  };

  export const PRICING_COMPETITORS: Array<{
    name: string;
    price: string;
    desc: string;
    highlight?: boolean;
  }>;

  export const PRICING_CTA: {
    title: string;
    text: string;
    href: string;
  };

  export const PRICING_TERMS: Array<Record<string, string>>;

  export const HOME_FAQ: { title: string };

  export const HOME_FINAL_CTA: {
    title: string;
    subtitle: string;
    cta: string;
    cta_href: string;
  };

  export const ABOUT: {
    title: string;
    subtitle?: string;
    intro: string;
    sections: Array<{
      title: string;
      subtitle?: string;
      intro?: string;
      content?: string;
      contentHtml?: string;
      agents?: Array<{ title: string; desc: string; descHtml?: string }>;
      values?: Array<{
        num: string;
        title: string;
        desc: string;
        descHtml?: string;
      }>;
      timeline?: Array<{
        title: string;
        content: string;
        contentHtml?: string;
      }>;
      email?: string;
    }>;
    email: string;
  };

  export const BLOG_CONFIG: {
    title: string;
    description: string;
    categories: string[];
    searchPlaceholder: string;
    loadMoreText: string;
    loadMoreLink: string;
    posts: Array<{
      slug: string;
      title: string;
      description: string;
      date: string;
      category: string;
      readTime: string;
      html: string;
      excerpt: string;
    }>;
  };

  // BLOG_POSTS_MAP values match BlogPostParsed (no slug, no excerpt)
  export const BLOG_POSTS_MAP: Record<
    string,
    {
      title: string;
      description: string;
      seo_title?: string;
      seo_description?: string;
      date: string;
      category: string;
      readTime: string;
      html: string;
    }
  >;

  export const FOOTER_SECTIONS: Array<{
    title: string;
    links: Array<{ label: string; href: string }>;
  }>;

  export const FOOTER_COPYRIGHT: string;

  // NAV_CONFIG is raw frontmatter from nav.md
  export const NAV_CONFIG: {
    logo_text: string;
    links: Array<{ label: string; href: string }>;
  };

  export const FAQ_ITEMS: Array<{
    question: string;
    answer: string;
    category?: string;
  }>;

  export const PRIVACY_POLICY: { html: string };
  export const TERMS_OF_SERVICE: { html: string };
  export const OPEN_SOURCE_NOTICES: { html: string };
}

// CSS imports
declare module '*.css';

// Preact-iso Router route props augmentation
declare namespace preact {
  namespace JSX {
    interface IntrinsicAttributes {
      path?: string;
      default?: boolean;
    }
  }
}
