/// <reference types="vite/client" />

// Virtual content module — types generated by the content loader at build time.
// All field names are camelCase. See src/data/types.ts for full interfaces.
// Uses import() syntax to avoid turning this file into a module.
declare module 'virtual:content' {
  export const SITE_CONFIG: import('../data/types').SiteConfig;
  export const ROUTE_META: Record<string, import('../data/types').RouteMeta>;
  export const HOME_HERO: import('../data/types').HeroContent;
  export const HOME_WHAT_YOU_GET: import('../data/types').WhatYouGetContent;
  export const HOME_PROBLEM: import('../data/types').ProblemContent;
  export const HOME_HOW_IT_WORKS: import('../data/types').HowItWorksContent;
  export const HOME_FEATURES: import('../data/types').FeaturesHeader;
  export const FEATURES: import('../data/types').Feature[];
  export const HOME_WHO_IS_THIS_FOR: import('../data/types').WhoIsThisForContent;
  export const HOME_PRICING: { title: string; subtitle: string };
  export const PRICING_TIERS: import('../data/types').PricingTier[];
  export const PRICING_FAQ: import('../data/types').PricingFaqItem[];
  export const PRICING_FEATURE_TABLE: import('../data/types').PricingFeatureTable;
  export const PRICING_COMPETITORS: import('../data/types').PricingCompetitor[];
  export const PRICING_CTA: import('../data/types').PricingCta;
  export const PRICING_TERMS: import('../data/types').PricingTerm[];
  export const HOME_FAQ: { title: string };
  export const HOME_FINAL_CTA: import('../data/types').FinalCta;
  export const ABOUT: import('../data/types').AboutContent;
  export const BLOG_CONFIG: import('../data/types').BlogConfig;
  export const BLOG_POSTS_MAP: Record<
    string,
    import('../data/types').BlogPostMapEntry
  >;
  export const FOOTER_SECTIONS: import('../data/types').FooterSection[];
  export const FOOTER_COPYRIGHT: string;
  export const NAV_CONFIG: import('../data/types').NavConfig;
  export const FAQ_ITEMS: import('../data/types').FaqItem[];
  export const PRIVACY_POLICY: import('../data/types').LegalPage;
  export const TERMS_OF_SERVICE: import('../data/types').LegalPage;
  export const OPEN_SOURCE_NOTICES: import('../data/types').LegalPage;
}

// CSS imports
declare module '*.css';

// Preact-iso Router route props augmentation
declare namespace preact {
  namespace JSX {
    interface IntrinsicAttributes {
      path?: string;
      default?: boolean;
    }
  }
}
